name: Enforce code coverage

on:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - backend/**

jobs:
  coverage:
    permissions:
      checks: write
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Download code
        uses: actions/checkout@v3

      - name: Executando testes...
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          working-directory: backend
          github-token: ${{ secrets.GH_TOKEN }}

      - name: Sucesso - Discord
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: "${{ github.actor }} mandou bem! Fez funcionalidades novas em {{ EVENT_PAYLOAD.repository.full_name }} e os testes estão passando."
