name: "coverage"

on:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - backend/**

jobs:
  coverage:
    permissions:
      checks: write
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          working-directory: backend
          github-token: ${{ secrets.GH_TOKEN }}
