name: Deploy API to Development env

on:
  push:
    branches:
      - develop
    # paths:
    #   - backend/**

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Download code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Run linters
        run: npm run lint

      # - name: Run tests
      #   run: npm test

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME_DEV }}
          heroku_email: ${{ secrets.HEROKU_APP_EMAIL }}
          appdir: backend

      - name: Success deploy - Discord
        if: success()
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: Jarvis
          DISCORD_AVATAR: https://static.wikia.nocookie.net/universocinematograficomarvel/images/b/b0/JuARaVeInSy.png/revision/latest?cb=20150919150102&path-prefix=pt
        uses: Ilshidur/action-discord@master
        with:
          args: "@everyone ${{ github.actor }} Fez um deploy com SUCESSO do {{ EVENT_PAYLOAD.repository.full_name }} em DESENVOLVIMENTO."

      - name: Failed deploy - Discord
        if: failure()
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: Jarvis
          DISCORD_AVATAR: https://static.wikia.nocookie.net/universocinematograficomarvel/images/b/b0/JuARaVeInSy.png/revision/latest?cb=20150919150102&path-prefix=pt
        uses: Ilshidur/action-discord@master
        with:
          args: "@everyone ${{ github.actor }} Tentou fazer um deploy com FALHA do {{ EVENT_PAYLOAD.repository.full_name }} em DESENVOLVIMENTO."
